version: '3.9'

services:

  grafana:
    image: grafana/grafana
    container_name: grafana-tapo
    ports:
      - 3000:3000
    networks:
      - tapo

  prometheus:
    image: prom/prometheus
    container_name: prometheus-tapo
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - tapo

  go-tapo-exporter:
    image: tess1o/go-tapo-exporter:latest-amd64
    container_name: go_tapo_exporter
    volumes:
      - ./config.json:/app/config.json:ro
    ports:
      - 8086:8086
    environment:
      - TAPO_EMAIL=CHANGE_ME
      - TAPO_PASSWORD=CHANGE_ME
      - TAPO_CONFIG_LOCATION=/app/config.json
    networks:
      - tapo

networks:
  tapo:
    driver: bridge